-- 文明6 Mod开发 - Requirement 深度参考
-- 从 DebugGameplay.sqlite 提取的完整 RequirementType 列表
--
-- 本文件按 16 分类组织，含 SQL 示例，适合阅读理解与复制使用。
-- 两者保留以支持不同使用场景。

-- ============================================
-- 一、Requirement 核心表结构
-- ============================================

-- Requirements: 定义单个条件
-- RequirementId: 唯一标识
-- RequirementType: 条件类型(见下方完整列表)
-- Likeliness/Impact: AI评估权重
-- Inverse: 是否反转结果(0=false, 1=true)

-- RequirementSets: 定义条件集合
-- RequirementSetId: 唯一标识
-- RequirementSetType: REQUIREMENTSET_TEST_ALL(AND) 或 REQUIREMENTSET_TEST_ANY(OR)

-- RequirementSetRequirements: 关联表
-- 将 Requirement 加入 RequirementSet

-- RequirementArguments: 条件参数
-- 类似 ModifierArguments, 存储条件的具体参数

-- ============================================
-- 二、Requirement 嵌套用法（Req 引用另一个 Req）
-- ============================================

-- 方式1: 使用 REQUIREMENT_REQUIREMENTSET_IS_MET 嵌套整个条件集
-- 这允许一个 RequirementSet 包含另一个 RequirementSet 的结果

-- 示例: 创建嵌套条件
-- 外层条件集: 要求满足"玩家是匈牙利" AND 满足内层条件集
-- 内层条件集: 要求满足"是首都地块" AND "地块产出大于5"

-- 步骤1: 创建内层条件集
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('REQSET_INNER_CAPITAL_HIGH_YIELD', 'REQUIREMENTSET_TEST_ALL');

-- 步骤2: 创建内层条件
INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('REQ_INNER_IS_CAPITAL', 'REQUIREMENT_PLOT_IS_CAPITAL');

INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('REQ_INNER_YIELD_GTE_5', 'REQUIREMENT_PLOT_YIELD_GTE');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQ_INNER_YIELD_GTE_5', 'YieldType', 'YIELD_FAITH');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQ_INNER_YIELD_GTE_5', 'Amount', '5');

-- 步骤3: 内层条件加入内层条件集
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQSET_INNER_CAPITAL_HIGH_YIELD', 'REQ_INNER_IS_CAPITAL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQSET_INNER_CAPITAL_HIGH_YIELD', 'REQ_INNER_YIELD_GTE_5');

-- 步骤4: 创建外层条件 - 引用内层条件集
INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('REQ_OUTER_NESTED_MET', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQ_OUTER_NESTED_MET', 'RequirementSetId', 'REQSET_INNER_CAPITAL_HIGH_YIELD');

-- 步骤5: 创建外层条件集
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('REQSET_OUTER_HUNGARY_SPECIAL', 'REQUIREMENTSET_TEST_ALL');

-- 步骤6: 外层条件加入外层条件集
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQSET_OUTER_HUNGARY_SPECIAL', 'REQ_OUTER_NESTED_MET');

-- ============================================
-- 三、Modifier 绑定 RequirementSet
-- ============================================

-- Modifiers 表有两个字段用于绑定条件:
-- OwnerRequirementSetId: 拥有者必须满足的条件
-- SubjectRequirementSetId: 目标对象必须满足的条件

-- 示例: 只有匈牙利玩家才能触发效果
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId)
VALUES (
    'HUNGARY_SPECIAL_MODIFIER',
    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',
    'REQSET_PLAYER_IS_HUNGARY'
);

-- 示例: 只有首都地块才能获得加成
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES (
    'CAPITAL_PLOT_MODIFIER',
    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',
    'REQSET_PLOT_IS_CAPITAL'
);

-- 示例: 双向条件 - 拥有者和目标都要满足
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId)
VALUES (
    'HUNGARY_CAPITAL_MODIFIER',
    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',
    'REQSET_PLAYER_IS_HUNGARY',    -- 匈牙利玩家
    'REQSET_PLOT_IS_CAPITAL'        -- 首都地块
);

-- ============================================
-- 四、完整 RequirementType 分类列表 (从 SQLite 提取)
-- ============================================

-- 【4.1 集合逻辑类】
-- REQUIREMENT_COLLECTION_ALL_MET - 集合中所有条件满足(AND)
-- REQUIREMENT_COLLECTION_ANY_MET - 集合中任一条件满足(OR)
-- REQUIREMENT_COLLECTION_COUNT_ATLEAST - 集合中至少N个条件满足
-- REQUIREMENT_COLLECTION_COUNT_EQUALS - 集合中恰好N个条件满足
-- REQUIREMENT_COLLECTION_COUNT_GREATERTHAN - 集合中超过N个条件满足
-- REQUIREMENT_REQUIREMENTSET_IS_MET - 指定条件集是否满足(用于嵌套)

-- 【4.2 玩家相关 PLAYER_*】
-- REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT - 玩家有特定文明/领袖特性
-- REQUIREMENT_PLAYER_HAS_TECHNOLOGY - 玩家拥有某科技
-- REQUIREMENT_PLAYER_HAS_CIVIC - 玩家拥有某市政
-- REQUIREMENT_PLAYER_HAS_BUILDING - 玩家拥有某建筑
-- REQUIREMENT_PLAYER_HAS_DISTRICT - 玩家拥有某区域
-- REQUIREMENT_PLAYER_HAS_GREAT_PERSON - 玩家拥有某伟人
-- REQUIREMENT_PLAYER_HAS_RESOURCE_IMPROVED - 玩家改良了某资源
-- REQUIREMENT_PLAYER_HAS_RESOURCE_OWNED - 玩家拥有某资源
-- REQUIREMENT_PLAYER_HAS_RESOURCE_VISIBILITY - 玩家可见某资源
-- REQUIREMENT_PLAYER_HAS_PANTHEON - 玩家创立万神殿
-- REQUIREMENT_PLAYER_IS_RELIGION_FOUNDER - 玩家创立宗教
-- REQUIREMENT_PLAYER_IS_SUZERAIN - 玩家是某城宗主
-- REQUIREMENT_PLAYER_IS_SUZERAIN_OF_X - 玩家是特定类型城邦宗主
-- REQUIREMENT_PLAYER_IS_AT_WAR - 玩家处于战争
-- REQUIREMENT_PLAYER_IS_AT_PEACE - 玩家处于和平
-- REQUIREMENT_PLAYER_IS_HUMAN - 玩家是人类
-- REQUIREMENT_PLAYER_IS_MAJOR - 玩家是主要文明
-- REQUIREMENT_PLAYER_IS_MINOR - 玩家是城邦
-- REQUIREMENT_PLAYER_IS_BARBARIAN - 玩家是蛮族
-- REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES - 领袖类型匹配
-- REQUIREMENT_PLAYER_CIVILIZATION_LEVEL - 文明等级匹配
-- REQUIREMENT_PLAYER_ERA_AT_LEAST - 玩家至少处于某时代
-- REQUIREMENT_PLAYER_HAS_GOLDEN_AGE - 玩家处于黄金时代
-- REQUIREMENT_PLAYER_HAS_DARK_AGE - 玩家处于黑暗时代
-- REQUIREMENT_PLAYER_BUILT_WONDER - 玩家建造了奇观
-- REQUIREMENT_PLAYER_BUILT_NEW_WONDER - 玩家建造了新奇观
-- REQUIREMENT_PLAYER_FINISHED_RESEARCH - 玩家完成了研究

-- 【4.3 城市相关 CITY_*】
-- REQUIREMENT_CITY_HAS_BUILDING - 城市有某建筑
-- REQUIREMENT_CITY_HAS_DISTRICT - 城市有某区域
-- REQUIREMENT_CITY_HAS_FEATURE - 城市有某地貌
-- REQUIREMENT_CITY_HAS_GOVERNOR - 城市有总督
-- REQUIREMENT_CITY_HAS_GOVERNOR_WITH_X_TITLES - 总督有X个头衔
-- REQUIREMENT_CITY_HAS_SPECIFIC_GOVERNOR_PROMOTION_TYPE - 总督有特定晋升
-- REQUIREMENT_CITY_HAS_NATIONAL_PARK - 城市有国家公园
-- REQUIREMENT_CITY_HAS_FULL_LOYALTY - 城市忠诚度满
-- REQUIREMENT_CITY_HAS_GARRISON_UNIT - 城市有驻军
-- REQUIREMENT_CITY_HAS_COUNTERSPY - 城市有反间谍
-- REQUIREMENT_CITY_HAS_X_POPULATION - 城市人口>=X
-- REQUIREMENT_CITY_HAS_X_SPECIALTY_DISTRICTS - 城市有X个 specialty 区域
-- REQUIREMENT_CITY_IS_ORIGINAL_CAPITAL - 城市是原始首都
-- REQUIREMENT_CITY_IS_ORIGINAL_OWNER - 城市是原始所有者
-- REQUIREMENT_CITY_IS_POWERED - 城市有电力
-- REQUIREMENT_CITY_FOLLOWS_RELIGION - 城市信仰某宗教
-- REQUIREMENT_CITY_FOLLOWS_PANTHEON - 城市信仰某万神殿
-- REQUIREMENT_CITY_CONVERTED - 城市被转换过宗教
-- REQUIREMENT_CITY_OCCUPIED - 城市被占领
-- REQUIREMENT_CITY_LIBERATED - 城市被解放
-- REQUIREMENT_CITY_RAZED - 城市被夷平
-- REQUIREMENT_CITY_HAS_ANY_WONDER - 城市有奇观
-- REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT - 城市有高相邻区域
-- REQUIREMENT_CITY_LOCATION_MATCHES - 城市位置匹配

-- 【4.4 地块相关 PLOT_*】
-- REQUIREMENT_PLOT_IS_CAPITAL - 地块是首都
-- REQUIREMENT_PLOT_IS_HILLS - 地块是丘陵
-- REQUIREMENT_PLOT_IS_COAST - 地块是海岸
-- REQUIREMENT_PLOT_IS_COASTAL_LAND - 地块是沿海陆地
-- REQUIREMENT_PLOT_IS_LAKE - 地块是湖泊
-- REQUIREMENT_PLOT_IS_MOUNTAIN - 地块是山脉
-- REQUIREMENT_PLOT_IS_FRESH_WATER - 地块有淡水
-- REQUIREMENT_PLOT_IS_IMPASSABLE - 地块不可通行
-- REQUIREMENT_PLOT_ADJACENT_TO_COAST - 地块邻接海岸
-- REQUIREMENT_PLOT_ADJACENT_TO_MOUNTAIN - 地块邻接山脉
-- REQUIREMENT_PLOT_ADJACENT_TO_RIVER - 地块邻接河流
-- REQUIREMENT_PLOT_ADJACENT_TO_NATURAL_WONDER - 地块邻接自然奇观
-- REQUIREMENT_PLOT_ADJACENT_TO_WONDER - 地块邻接人造奇观
-- REQUIREMENT_PLOT_ADJACENT_TO_OWNER - 地块邻接所有者领土
-- REQUIREMENT_PLOT_ADJACENT_TO_OWNER_AT_WAR - 地块邻接战争中的所有者
-- REQUIREMENT_PLOT_ADJACENT_FRIENDLY_TERRITORY - 地块邻接友好领土
-- REQUIREMENT_PLOT_HAS_ANY_DISTRICT - 地块有任何区域
-- REQUIREMENT_PLOT_HAS_ANY_IMPROVEMENT - 地块有任何改良
-- REQUIREMENT_PLOT_HAS_ANY_FEATURE - 地块有任何地貌
-- REQUIREMENT_PLOT_HAS_ANY_RESOURCE - 地块有任何资源
-- REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES - 地块区域类型匹配
-- REQUIREMENT_PLOT_DISTRICT_TAG_MATCHES - 地块区域标签匹配
-- REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES - 地块改良类型匹配
-- REQUIREMENT_PLOT_IMPROVEMENT_TAG_MATCHES - 地块改良标签匹配
-- REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES - 地块地貌类型匹配
-- REQUIREMENT_PLOT_FEATURE_TAG_MATCHES - 地块地貌标签匹配
-- REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES - 地块资源类型匹配
-- REQUIREMENT_PLOT_RESOURCE_CLASS_TYPE_MATCHES - 地块资源类别匹配
-- REQUIREMENT_PLOT_RESOURCE_VISIBLE - 地块资源可见
-- REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES - 地块地形类型匹配
-- REQUIREMENT_PLOT_TERRAIN_CLASS_MATCHES - 地块地形类别匹配
-- REQUIREMENT_PLOT_NEAR_CAPITAL - 地块靠近首都
-- REQUIREMENT_PLOT_WONDER_IS_ERA - 地块奇观属于某时代
-- REQUIREMENT_PLOT_IS_OWNER_CAPITAL_CONTINENT - 地块与首都同大陆
-- REQUIREMENT_PLOT_ADJACENT_BUILDING_TYPE_MATCHES - 邻接建筑类型
-- REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES - 邻接区域类型
-- REQUIREMENT_PLOT_ADJACENT_FEATURE_TYPE_MATCHES - 邻接地貌类型
-- REQUIREMENT_PLOT_ADJACENT_IMPROVEMENT_TYPE_MATCHES - 邻接改良类型
-- REQUIREMENT_PLOT_ADJACENT_RESOURCE_CLASS_TYPE_MATCHES - 邻接资源类别
-- REQUIREMENT_PLOT_ADJACENT_TERRAIN_TYPE_MATCHES - 邻接地形类型
-- REQUIREMENT_PLOT_ADJACENT_FRIENDLY_UNIT_TAG_MATCHES - 邻接友好单位标签
-- REQUIREMENT_PLOT_ADJACENT_FRIENDLY_UNIT_TYPE_MATCHES - 邻接友好单位类型
-- REQUIREMENT_PLOT_ADJACENT_UNIT_TYPE_MATCHES - 邻接单位类型
-- REQUIREMENT_PLOT_IS_APPEAL_BETWEEN - 地块吸引力在某范围
-- REQUIREMENT_PLOT_PROPERTY_MATCHES - 地块属性匹配

-- 【4.5 单位相关 UNIT_*】
-- REQUIREMENT_UNIT_TYPE_MATCHES - 单位类型匹配
-- REQUIREMENT_UNIT_TAG_MATCHES - 单位标签匹配
-- REQUIREMENT_UNIT_DOMAIN_MATCHES - 单位领域匹配
-- REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES - 单位晋升类别匹配
-- REQUIREMENT_UNIT_HAS_PROMOTION - 单位有某晋升
-- REQUIREMENT_UNIT_HAS_ABILITY - 单位有某能力
-- REQUIREMENT_UNIT_FORMATION_CLASS_MATCHES - 单位编队类别匹配
-- REQUIREMENT_UNIT_ERA_TYPE_MATCHES - 单位时代匹配
-- REQUIREMENT_UNIT_IS_EMBARKED - 单位已上船
-- REQUIREMENT_UNIT_IN_FORMATION - 单位在编队中
-- REQUIREMENT_UNIT_IN_OWNER_TERRITORY - 单位在己方领土
-- REQUIREMENT_UNIT_IN_ENEMY_TERRITORY - 单位在敌方领土
-- REQUIREMENT_UNIT_IN_EMERGENCY_TARGET_TERRITORY - 单位在紧急目标领土
-- REQUIREMENT_UNIT_ON_COAST - 单位在海岸
-- REQUIREMENT_UNIT_ON_HOME_CONTINENT - 单位在 homeland 大陆
-- REQUIREMENT_UNIT_IS_ADMIRAL - 单位是海军统帅
-- REQUIREMENT_UNIT_IS_ENGINEER - 单位是军事工程师
-- REQUIREMENT_UNIT_IS_GREAT_GENERAL - 单位是大将军
-- REQUIREMENT_UNIT_IS_BUILDER - 单位是建造者
-- REQUIREMENT_UNIT_IS_SPY - 单位是间谍
-- REQUIREMENT_UNIT_IS_MELEE - 单位是近战
-- REQUIREMENT_UNIT_IS_RANGED - 单位是远程
-- REQUIREMENT_UNIT_IS_SIEGE - 单位是攻城
-- REQUIREMENT_UNIT_IS_ANTI_CAV - 单位是反骑兵
-- REQUIREMENT_UNIT_IS_LIGHT_CAV - 单位是轻骑兵
-- REQUIREMENT_UNIT_IS_HEAVY_CAV - 单位是重骑兵
-- REQUIREMENT_UNIT_IS_ROCK_BAND - 单位是摇滚乐队
-- REQUIREMENT_UNIT_IS_SUBMARINE - 单位是潜艇
-- REQUIREMENT_UNIT_IS_BARBARIAN - 单位是蛮族
-- REQUIREMENT_UNIT_IS_COMBAT - 单位是战斗单位
-- REQUIREMENT_UNIT_IS_LEVIED - 单位是雇佣的
-- REQUIREMENT_UNIT_IS_HETAIROI - 单位是伙伴骑兵
-- REQUIREMENT_UNIT_DAMAGE_MINIMUM - 单位最低伤害
-- REQUIREMENT_UNIT_ADJACENT_TO_OWNER_TERRITORY - 单位邻接己方领土
-- REQUIREMENT_UNIT_PLOT_HAS_NATIONAL_PARK - 单位地块有国家公园
-- REQUIREMENT_UNIT_PLOT_HAS_ANY_DISTRICT - 单位地块有区域
-- REQUIREMENT_UNIT_PLOT_HAS_DISTRICT_SAME_OWNER - 单位地块有同所有者区域

-- 【4.6 战斗相关 COMBAT_*】
-- REQUIREMENT_COMBAT_ATTACKER_IS_PLAYER - 攻击者是某玩家
-- REQUIREMENT_COMBAT_DEFENDER_IS_PLAYER - 防御者是某玩家
-- REQUIREMENT_COMBAT_ATTACKER_IS_EMERGENCY_MEMBER - 攻击者是紧急成员
-- REQUIREMENT_COMBAT_DEFENDER_IS_EMERGENCY_MEMBER - 防御者是紧急成员
-- REQUIREMENT_COMBAT_ATTACKER_IS_EMERGENCY_MEMBER_WITH_SCORE - 攻击者是紧急成员且有分数
-- REQUIREMENT_COMBAT_DEFENDER_IS_EMERGENCY_MEMBER_WITH_SCORE - 防御者是紧急成员且有分数
-- REQUIREMENT_COMBAT_TYPE_MATCHES - 战斗类型匹配
-- REQUIREMENT_COMBAT_VERSUS_TYPE_MATCHES - 战斗对阵类型匹配
-- REQUIREMENT_COMBAT_ENEMY_NOT_ALLIANCE_RELIGION - 敌人非联盟宗教
-- REQUIREMENT_COMBAT_OTHER_PLAYER_IS_HUMAN - 对手是人类
-- REQUIREMENT_COMBAT_RESULTS_ATTACKING_UNIT_HAS_TAG - 攻击单位有标签
-- REQUIREMENT_COMBAT_RESULTS_DEFENDER_IS_DISTRICT - 防御者是区域
-- REQUIREMENT_COMBAT_RESULTS_UNIT_DIED - 单位死亡

-- 【4.7 对手相关 OPPONENT_*】
-- REQUIREMENT_OPPONENT_UNIT_TYPE_MATCHES - 对手单位类型匹配
-- REQUIREMENT_OPPONENT_UNIT_PROMOTION_CLASS_MATCHES - 对手单位晋升类别匹配
-- REQUIREMENT_OPPONENT_UNIT_DOMAIN_MATCHES - 对手单位领域匹配
-- REQUIREMENT_OPPONENT_UNIT_TAG_MATCHES - 对手单位标签匹配
-- REQUIREMENT_OPPONENT_IS_BARBARIAN - 对手是蛮族
-- REQUIREMENT_OPPONENT_IS_MINOR_CIV - 对手是城邦
-- REQUIREMENT_OPPONENT_IS_FREE_CITY - 对手是自由城市
-- REQUIREMENT_OPPONENT_IS_DISTRICT - 对手是区域
-- REQUIREMENT_OPPONENT_IS_FORTIFIED - 对手已驻防
-- REQUIREMENT_OPPONENT_IS_WOUNDED - 对手受伤
-- REQUIREMENT_OPPONENT_IS_STRONGER - 对手更强
-- REQUIREMENT_OPPONENT_IS_OTHER_RELIGION - 对手是其他宗教
-- REQUIREMENT_OPPONENT_ERA_AT_LEAST - 对手至少某时代
-- REQUIREMENT_OPPONENT_ERA_AGE_MATCHES - 对手时代匹配
-- REQUIREMENT_OPPONENT_WAS_KILLED - 对手被击杀

-- 【4.8 外交关系相关】
-- REQUIREMENT_ALLY - 是盟友
-- REQUIREMENT_DECLARED_FRIEND - 是宣友状态
-- REQUIREMENT_DEFENSIVE_PACT - 有防御同盟
-- REQUIREMENT_OPEN_BORDERS - 有开放边界
-- REQUIREMENT_DENOUNCED - 被谴责
-- REQUIREMENT_DENOUNCED_FRIEND - 被朋友谴责
-- REQUIREMENT_MET - 已遇见
-- REQUIREMENT_NOT_MET - 未遇见
-- REQUIREMENT_NEVER_MET - 从未遇见
-- REQUIREMENT_DELEGATION - 有代表团
-- REQUIREMENT_RESIDENT_EMBASSY - 有大使馆
-- REQUIREMENT_HAD_FRIENDLY_MEETING - 有过友好会面
-- REQUIREMENT_DEMAND_RECEIVED - 收到过要求
-- REQUIREMENT_PLAYER_IS_NEIGHBOR - 是邻国
-- REQUIREMENT_PLAYER_IS_SAME_RELIGION - 同宗教
-- REQUIREMENT_PLAYER_IS_SAME_GOVERNMENT - 同政体
-- REQUIREMENT_PLAYER_SHARES_HOME_CONTINENT - 同 homeland 大陆
-- REQUIREMENT_PLAYER_IS_TEAM_MEMBER - 同队伍成员

-- 【4.9 时代与游戏进度相关】
-- REQUIREMENT_GAME_ERA_IS - 游戏处于某时代
-- REQUIREMENT_GAME_ERA_ATLEAST - 游戏至少某时代
-- REQUIREMENT_GAME_ERA_ATMOST - 游戏至多某时代
-- REQUIREMENT_GAME_TURN_ATLEAST - 游戏回合至少
-- REQUIREMENT_GAME_TURN_MAX_REACHED - 游戏达到最大回合
-- REQUIREMENT_GAME_VICTORY_ENABLED - 某胜利类型启用
-- REQUIREMENT_GAME_HAS_CIVILIZATION_OR_LEADER_TRAIT - 游戏有某文明/领袖特性
-- REQUIREMENT_GAME_IS_MULTIPLAYER - 游戏是多人模式
-- REQUIREMENT_GAME_CLIMATE_CHANGE_LEVEL_AT_LEAST - 气候变化等级至少

-- 【4.10 区域与建筑相关 DISTRICT_*/BUILDING_*】
-- REQUIREMENT_DISTRICT_TYPE_MATCHES - 区域类型匹配
-- REQUIREMENT_DISTRICT_DEFENDER - 区域防御者
-- REQUIREMENT_DISTRICT_ZOMBIE_EFFECT_PERCENT_CHANCE - 区域僵尸效果概率
-- REQUIREMENT_BUILDING_TYPE_MATCHES - 建筑类型匹配
-- REQUIREMENT_BUILDING_TAG_MATCHES - 建筑标签匹配
-- REQUIREMENT_BUILDING_DISCOUNT_RESOURCE - 建筑折扣资源

-- 【4.11 资源与改良相关】
-- REQUIREMENT_CITY_GROWTH_RESOURCE - 城市成长资源
-- REQUIREMENT_CITY_GROWTH_INDUSTRY - 城市成长工业
-- REQUIREMENT_CULTURE_BONUS_RESOURCE - 文化奖励资源
-- REQUIREMENT_FAITH_BONUS_RESOURCE - 信仰奖励资源
-- REQUIREMENT_GOLD_BONUS_RESOURCE - 金币奖励资源
-- REQUIREMENT_SCIENCE_BONUS_RESOURCE - 科技奖励资源
-- REQUIREMENT_MILITARY_DISCOUNT_RESOURCE - 军事折扣资源
-- REQUIREMENT_CIVILIAN_DISCOUNT_RESOURCE - 民用折扣资源

-- 【4.12 伟人相关 GREAT_PERSON_*】
-- REQUIREMENT_GREAT_PERSON_TYPE_MATCHES - 伟人类型匹配
-- REQUIREMENT_PLAYER_CAN_EVER_EARN_GREAT_PERSON_CLASS - 玩家可获得某类伟人
-- REQUIREMENT_PLAYER_GOT_GREAT_PERSON - 玩家获得过伟人

-- 【4.13 联盟相关 ALLIANCE_*】
-- REQUIREMENT_ALLIANCE_AT_WAR_WITH_COMBAT_TARGET - 联盟与战斗目标交战
-- REQUIREMENT_ALLIANCE_CITY_HAS_TRADE_ROUTE_WITH_ALLY - 联盟城市与盟友有贸易路线
-- REQUIREMENT_ALLIANCE_SHARES_SECRET_SOCIETY - 联盟共享秘密结社
-- REQUIREMENT_PLAYER_HAS_ACTIVE_ALLIANCE_OF_AT_LEAST_LEVEL - 玩家有至少某等级的活跃联盟

-- 【4.14 紧急事件相关 EMERGENCY_*】
-- REQUIREMENT_PLAYER_AT_WAR_WITH_EMERGENCY_MEMBER - 玩家与紧急成员交战
-- REQUIREMENT_PLAYER_IS_EMERGENCY_TARGET - 玩家是紧急目标
-- REQUIREMENT_PLAYER_IS_EMERGENCY_MEMBER_WITH_SCORE - 玩家是紧急成员且有分数
-- REQUIREMENT_PLAYER_GOT_FIRST_PLACE_IN_EMERGENCY - 玩家在紧急事件中获得第一
-- REQUIREMENT_PLAYER_GOT_HIGH_TIER_SCORE_IN_EMERGENCY - 玩家在紧急事件中获得高分
-- REQUIREMENT_PLAYER_GOT_LOW_TIER_SCORE_IN_EMERGENCY - 玩家在紧急事件中获得低分
-- REQUIREMENT_PLAYER_IN_JOINT_EMERGENCY - 玩家在联合紧急事件中
-- REQUIREMENT_PLAYER_IS_AT_LEAST_ALLIANCE_LEVEL_WITH_EMERGENCY_PLAYER - 与紧急玩家至少某联盟等级
-- REQUIREMENT_PLAYER_CITY_STATE_PROTECTOR - 玩家是城邦保护者

-- 【4.15 贸易路线相关 TRADE_ROUTE_*】
-- REQUIREMENT_TRADE_ROUTE_BETWEEN_ALLIANCE_PARTNERS - 贸易路线在联盟伙伴间
-- REQUIREMENT_TRADE_ROUTE_BETWEEN_EMERGENCY_MEMBER_AND_TARGET - 贸易路线在紧急成员与目标间
-- REQUIREMENT_TRADE_ROUTE_BETWEEN_EMERGENCY_MEMBERS - 贸易路线在紧急成员间
-- REQUIREMENT_TRADE_ROUTE_DESTINATION_IS_CITY_STATE - 贸易路线目的地是城邦

-- 【4.16 其他特殊】
-- REQUIREMENT_ALWAYS_MET - 总是满足
-- REQUIREMENT_MODIFIER - 修改器条件(特殊用途)
-- REQUIREMENT_RANDOM_VALUE_LESS_THAN_OR_EQUAL_TO - 随机值小于等于
-- REQUIREMENT_NEAR_CULTURE_BORDER - 靠近文化边界
-- REQUIREMENT_NEAR_RELIGIOUS_CITY - 靠近宗教城市
-- REQUIREMENT_CULTURE_BOMBED - 被文化炸弹炸过
-- REQUIREMENT_ESPIONAGE_DETECTED - 间谍活动被侦测
-- REQUIREMENT_FOUNDED_NO_RELIGION - 未创立宗教
-- REQUIREMENT_PLAYER_ATTACKED_CONTINENT - 玩家攻击过某大陆
-- REQUIREMENT_PLAYER_BUILT_NEW_WONDER - 玩家建造了新奇观
-- REQUIREMENT_PLAYER_PEACEFUL_ON_CONTINENT - 玩家在某大陆和平
-- REQUIREMENT_PLAYER_ON_NON_HOME_CONTINENT - 玩家在非 homeland 大陆
-- REQUIREMENT_PLAYER_COASTAL_CITIES - 玩家有沿海城市
-- REQUIREMENT_PLAYER_MOUNTAIN_CITIES - 玩家有山地城市
-- REQUIREMENT_PLAYER_CITY_STATE_PROTECTORS - 玩家是多个城邦保护者

-- ============================================
-- 五、匈牙利首都+3信仰完整示例（带 RequirementSet）
-- ============================================

-- 完整 SQL: 匈牙利文明，首都地块+3信仰

-- 1. 创建 RequirementSet：检测玩家是匈牙利
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('REQSET_PLAYER_IS_HUNGARY', 'REQUIREMENTSET_TEST_ALL');

-- 2. 创建 Requirement：玩家文明是匈牙利
INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('REQ_PLAYER_CIVILIZATION_HUNGARY', 'REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT');

-- 3. 添加 Requirement 参数
INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQ_PLAYER_CIVILIZATION_HUNGARY', 'CivilizationType', 'CIVILIZATION_HUNGARY');

-- 4. Requirement 加入 RequirementSet
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQSET_PLAYER_IS_HUNGARY', 'REQ_PLAYER_CIVILIZATION_HUNGARY');

-- 5. 创建首都地块条件集
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('REQSET_PLOT_IS_CAPITAL', 'REQUIREMENTSET_TEST_ALL');

-- 6. 创建 Requirement：地块是首都
INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('REQ_PLOT_IS_CAPITAL', 'REQUIREMENT_PLOT_IS_CAPITAL');

-- 7. Requirement 加入条件集
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQSET_PLOT_IS_CAPITAL', 'REQ_PLOT_IS_CAPITAL');

-- 8. 创建 Modifier（绑定双向条件）
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId)
VALUES (
    'HUNGARY_CAPITAL_PLOT_FAITH_PLUS_3',
    'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',
    'REQSET_PLAYER_IS_HUNGARY',     -- 拥有者条件：匈牙利玩家
    'REQSET_PLOT_IS_CAPITAL'         -- 目标条件：首都地块
);

-- 9. 添加 Modifier 参数
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES 
    ('HUNGARY_CAPITAL_PLOT_FAITH_PLUS_3', 'YieldType', 'YIELD_FAITH'),
    ('HUNGARY_CAPITAL_PLOT_FAITH_PLUS_3', 'Amount', '3');

-- 10. 绑定到匈牙利 Trait
INSERT INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_CIVILIZATION_PEARL_DANUBE', 'HUNGARY_CAPITAL_PLOT_FAITH_PLUS_3');
