-- civilopedia.sql 文明6百科常量数据表
CREATE DATABASE IF NOT EXISTS civilization6_civilopedia DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE civilization6_civilopedia;

DROP TABLE IF EXISTS civilopedia_constants;
CREATE TABLE civilopedia_constants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category ENUM('intro','color','icon') NOT NULL COMMENT '常量分类：介绍、颜色、图标',
    constant_name VARCHAR(255) NOT NULL COMMENT '常量标识名',
    raw_text TEXT NOT NULL COMMENT '原始文本内容',
    remark VARCHAR(500) DEFAULT NULL COMMENT '补充说明',
    UNIQUE KEY uk_const_name_cat (constant_name, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文明6 Civilopedia 颜色、图标常量清单';

-- 插入开篇介绍文本
INSERT INTO civilopedia_constants(category,constant_name,raw_text,remark) VALUES
('intro','main_intro',
'CIVILOPEDIA

Introduction
Welcome to the Civilopedia for Sid Meier\'s Civilization VI! Here you will find detailed descriptions of all aspects of the game. Clicking on the tabs on the top edge of the screen will take you to the various major sections of the Civilopedia. The Navigation Bar on the left side of the screen will display the various entries within a section. Click on an entry to go directly there.

Line break usage, replace () with square brackets:
(NEWLINE)

Color usage, replace () with square brackets:
(COLOR_Blue)Text goes here(ENDCOLOR)',
'页面开头说明、格式使用规则'
);

-- 颜色常量批量插入
INSERT INTO civilopedia_constants(category,constant_name,raw_text,remark) VALUES
('color','COLOR_Blue','COLOR_Blue','基础蓝色'),
('color','COLOR_Civ6DarkRed','COLOR_Civ6DarkRed','文明6暗红色'),
('color','COLOR_Civ6Green','COLOR_Civ6Green','文明6绿色'),
('color','COLOR_Civ6Red','COLOR_Civ6Red','文明6红色'),
('color','COLOR_Civ6Yellow','COLOR_Civ6Yellow','文明6黄色'),
('color','COLOR_FLOAT_CULTURE','COLOR_FLOAT_CULTURE','文化浮动数值色'),
('color','COLOR_FLOAT_DIPLOMATIC','COLOR_FLOAT_DIPLOMATIC','外交浮动数值色'),
('color','COLOR_FLOAT_FAITH','COLOR_FLOAT_FAITH','信仰浮动数值色'),
('color','COLOR_FLOAT_FOOD','COLOR_FLOAT_FOOD','食物浮动数值色'),
('color','COLOR_FLOAT_GOLD','COLOR_FLOAT_GOLD','金币浮动数值色'),
('color','COLOR_FLOAT_MILITARY','COLOR_FLOAT_MILITARY','军事浮动数值色'),
('color','COLOR_FLOAT_PRODUCTION','COLOR_FLOAT_PRODUCTION','产能浮动数值色'),
('color','COLOR_FLOAT_SCIENCE','COLOR_FLOAT_SCIENCE','科技浮动数值色'),
('color','COLOR_GREEN','COLOR_GREEN','基础绿色'),
('color','COLOR_LIGHTBLUE','COLOR_LIGHTBLUE','浅蓝色'),
('color','COLOR_MEDIUM_GREEN','COLOR_MEDIUM_GREEN','中绿色'),
('color','COLOR_RED','COLOR_RED','基础红色'),
('color','COLOR_WHITE','COLOR_WHITE','基础白色'),
('color','COLOR:131,147,158,255','COLOR:131,147,158,255','RGBA颜色值'),
('color','COLOR:255,255,255,255','COLOR:255,255,255,255','纯白RGBA'),
('color','COLOR:72,39,111,255','COLOR:72,39,111,255','紫调RGBA'),
('color','COLORButtonCS','COLORButtonCS','按钮控件色'),
('color','color:ChatMessage_Global','color:ChatMessage_Global','全局聊天文字色'),
('color','color:ChatMessage_Help','color:ChatMessage_Help','帮助聊天文字色'),
('color','color:ChatMessage_Team','color:ChatMessage_Team','队伍聊天文字色'),
('color','color:ChatMessage_Whisper','color:ChatMessage_Whisper','私聊聊天文字色'),
('color','color:ChatPlayerName','color:ChatPlayerName','玩家名聊天色'),
('color','COLOR:Civ6Blue','COLOR:Civ6Blue','文明6蓝色'),
('color','COLOR:Civ6Red','COLOR:Civ6Red','文明6红色'),
('color','COLOR:Civ6Yellow','COLOR:Civ6Yellow','文明6黄色'),
('color','COLOR:ConnectionStatus_Connected','COLOR:ConnectionStatus_Connected','已连接状态色'),
('color','COLOR:ConnectionStatus_NotModReady','COLOR:ConnectionStatus_NotModReady','模组未就绪状态色'),
('color','COLOR:ConnectionStatus_Resyncing','COLOR:ConnectionStatus_Resyncing','重同步状态色'),
('color','COLOR:DiplomaticLabelCS','COLOR:DiplomaticLabelCS','外交标签控件色'),
('color','COLOR:FoodDark','COLOR:FoodDark','食物深色'),
('color','color:Green','color:Green','绿色'),
('color','color:Happiness','color:Happiness','幸福度颜色'),
('color','color:ModStatusGreen','color:ModStatusGreen','模组正常状态绿'),
('color','color:ModStatusYellow','color:ModStatusYellow','模组警告状态黄'),
('color','COLOR:Red','COLOR:Red','红色'),
('color','COLOR:ResCultureLabelCS','COLOR:ResCultureLabelCS','文化资源标签色'),
('color','COLOR:ResFaithLabelCS','COLOR:ResFaithLabelCS','信仰资源标签色'),
('color','COLOR:ResFoodLabelCS','COLOR:ResFoodLabelCS','食物资源标签色'),
('color','COLOR:ResGoldLabelCS','COLOR:ResGoldLabelCS','金币资源标签色'),
('color','COLOR:ResMilitaryLabelCS','COLOR:ResMilitaryLabelCS','军事资源标签色'),
('color','COLOR:ResProductionLabelCS','COLOR:ResProductionLabelCS','产能资源标签色'),
('color','COLOR:ResScienceLabelCS','COLOR:ResScienceLabelCS','科技资源标签色'),
('color','COLOR:StagingStatus_Invalid','COLOR:StagingStatus_Invalid','暂存无效状态色'),
('color','ColorStatBadCS','ColorStatBadCS','负面数值统计色'),
('color','COLOR:StatGoodCS','COLOR:StatGoodCS','正面数值统计色'),
('color','COLOR:SuzerainDark','COLOR:SuzerainDark','宗主国深色');

-- 图标使用说明插入
INSERT INTO civilopedia_constants(category,constant_name,raw_text,remark) VALUES
('intro','icon_usage_rule',
'Icon usage, replace () with square brackets:
(ICON_Bullet)',
'图标格式规则：圆括号替换为方括号'
);

-- 图标常量，选取核心条目，完整列表按下方批量INSERT；限于篇幅先给出结构+示例，完整图标可沿用相同INSERT格式追加：
INSERT INTO civilopedia_constants(category,constant_name,raw_text,remark) VALUES
('icon','ICON_Bullet','ICON_Bullet','项目符号图标'),
('icon','ICON_BulletGlow','ICON_BulletGlow','发光项目符号'),
('icon','ICON_You','ICON_You','玩家自身标识'),
('icon','ICON_Bolt','ICON_Bolt','闪电图标'),
('icon','ICON_OnlinePip','ICON_OnlinePip','在线状态小点'),
('icon','ICON_OnlineGreenPingPip','ICON_OnlineGreenPingPip','正常延迟在线小点'),
('icon','ICON_PausedGreenPingPip','ICON_PausedGreenPingPip','暂停绿延迟小点'),
('icon','ICON_HotjoiningPip','ICON_HotjoiningPip','中途加入状态点'),
('icon','ICON_ResyncingPip','ICON_ResyncingPip','重同步状态点'),
('icon','ICON_NotModReadyPip','ICON_NotModReadyPip','模组未就绪点'),
('icon','ICON_OnlineYellowPingPig','ICON_OnlineYellowPingPig','高延迟在线黄点'),
('icon','ICON_PausedYellowPingPig','ICON_PausedYellowPingPig','暂停高延迟黄点'),
('icon','ICON_OfflineRedPingPig','ICON_OfflineRedPingPig','离线红点'),
('icon','ICON_PausedPip','ICON_PausedPip','通用暂停点'),
('icon','ICON_Plus','ICON_Plus','加号图标'),
('icon','ICON_New','ICON_New','新增标识'),
('icon','ICON_Checkmark','ICON_Checkmark','勾选'),
('icon','ICON_Exclamation','ICON_Exclamation','感叹号'),
('icon','ICON_CheckmarkBlue','ICON_CheckmarkBlue','蓝色勾选'),
('icon','ICON_CheckSuccess','ICON_CheckSuccess','校验成功'),
('icon','ICON_CheckFail','ICON_CheckFail','校验失败'),
('icon','ICON_Ready','ICON_Ready','就绪'),
('icon','ICON_Not','ICON_Not','否定标识'),
('icon','ICON_GoingTo','ICON_GoingTo','即将执行'),
('icon','ICON_Therefore','ICON_Therefore','推导标识'),
('icon','ICON_Revert','ICON_Revert','回退'),
('icon','ICON_PressureUp','ICON_PressureUp','压力上升'),
('icon','ICON_PressureUpLarge','ICON_PressureUpLarge','大幅压力上升'),
('icon','ICON_PressureHigh','ICON_PressureHigh','高压'),
('icon','ICON_PressureMedium','ICON_PressureMedium','中压'),
('icon','ICON_PressureLow','ICON_PressureLow','低压'),
('icon','ICON_PressureDown','ICON_PressureDown','压力下降'),
('icon','ICON_PressureDownLarge','ICON_PressureDownLarge','大幅压力下降'),
('icon','ICON_DownloadContent','ICON_DownloadContent','下载内容'),
('icon','ICON_LocationPip','ICON_LocationPip','位置标记点'),
('icon','ICON_ShowMe','ICON_ShowMe','定位跳转'),
('icon','ICON_Turn','ICON_Turn','回合'),
('icon','ICON_Reports','ICON_Reports','报表'),
('icon','ICON_List','ICON_List','列表'),
('icon','ICON_Host','ICON_Host','房主'),
('icon','ICON_Global','ICON_Global','全局'),
('icon','ICON_Whisper','ICON_Whisper','私聊'),
('icon','ICON_Team','ICON_Team','队伍'),
('icon','ICON_AdditionalContent','ICON_AdditionalContent','额外内容'),
('icon','ICON_Culture','ICON_Culture','文化'),
('icon','ICON_CivicBoosted','ICON_CivicBoosted','市政提速'),
('icon','ICON_Faith','ICON_Faith','信仰'),
('icon','ICON_Food','ICON_Food','食物'),
('icon','ICON_FoodDeficit','ICON_FoodDeficit','食物短缺'),
('icon','ICON_FoodPerTurn','ICON_FoodPerTurn','每回合食物'),
('icon','ICON_FoodSurplus','ICON_FoodSurplus','食物盈余'),
('icon','ICON_Gold','ICON_Gold','金币'),
('icon','ICON_Production','ICON_Production','产能'),
('icon','ICON_ProductionQueue','ICON_ProductionQueue','生产队列'),
('icon','ICON_Science','ICON_Science','科技'),
('icon','ICON_TechBoosted','ICON_TechBoosted','科技提速'),
('icon','ICON_Amenities','ICON_Amenities','宜居度'),
('icon','ICON_AmenitiesInsufficient','ICON_AmenitiesInsufficient','宜居不足'),
('icon','ICON_Housing','ICON_Housing','住房'),
('icon','ICON_HousingInsufficient','ICON_HousingInsufficient','住房不足'),
('icon','ICON_Terrain','ICON_Terrain','地形'),
('icon','ICON_Movement','ICON_Movement','移动力'),
('icon','ICON_Unit','ICON_Unit','单位'),
('icon','ICON_Position','ICON_Position','坐标位置'),
('icon','ICON_Ability','ICON_Ability','能力'),
('icon','ICON_Promotion','ICON_Promotion','晋升'),
('icon','ICON_Strength','ICON_Strength','战力'),
('icon','ICON_Range','ICON_Range','射程'),
('icon','ICON_Ranged','ICON_Ranged','远程攻击'),
('icon','ICON_Bombard','ICON_Bombard','轰击'),
('icon','ICON_Army','ICON_Army','军队'),
('icon','ICON_Corps_Large','ICON_Corps_Large','大军团'),
('icon','ICON_Fortify','ICON_Fortify','驻扎设防'),
('icon','ICON_Fortified','ICON_Fortified','已设防'),
('icon','ICON_Pillaged','ICON_Pillaged','被劫掠'),
('icon','ICON_UnderSiege','ICON_UnderSiege','被围困'),
('icon','ICON_Occupied','ICON_Occupied','被占领'),
('icon','ICON_Razed','ICON_Razed','城市夷平'),
('icon','ICON_Nuclear','ICON_Nuclear','核武器'),
('icon','ICON_Thermonuclear','ICON_Thermonuclear','热核装置'),
('icon','ICON_Barbarian','ICON_Barbarian','野蛮人'),
('icon','ICON_Charges','ICON_Charges','使用次数/充能'),
('icon','ICON_Capital','ICON_Capital','首都'),
('icon','ICON_Government','ICON_Government','政体'),
('icon','ICON_Policy','ICON_Policy','政策卡'),
('icon','ICON_Religion','ICON_Religion','宗教'),
('icon','ICON_Citizen','ICON_Citizen','公民人口'),
('icon','ICON_ThemeBonus','ICON_ThemeBonus','主题化加成'),
('icon','ICON_Tourism','ICON_Tourism','旅游业绩'),
('icon','ICON_TradingPost','ICON_TradingPost','贸易站'),
('icon','ICON_TradeRoute','ICON_TradeRoute','贸易路线'),
('icon','ICON_CityStateQuest','ICON_CityStateQuest','城邦任务'),
('icon','ICON_Envoy','ICON_Envoy','使者'),
('icon','ICON_InfluencePerTurn','ICON_InfluencePerTurn','每回合影响力'),
('icon','ICON_District_ACROPOLIS','ICON_District_ACROPOLIS','卫城区域'),
('icon','ICON_District_AQUEDUCT','ICON_District_AQUEDUCT','水渠'),
('icon','ICON_District_BATH','ICON_District_BATH','浴场'),
('icon','ICON_District_CAMPUS','ICON_District_CAMPUS','学院'),
('icon','ICON_District_CITY_CENTER','ICON_District_CITY_CENTER','市中心'),
('icon','ICON_District_COMMERCIAL_HUB','ICON_District_COMMERCIAL_HUB','商业中心'),
('icon','ICON_District_ENCAMPMENT','ICON_District_ENCAMPMENT','军营'),
('icon','ICON_District_ENTERTAINMENT','ICON_District_ENTERTAINMENT','娱乐中心'),
('icon','ICON_District_HANSA','ICON_District_HANSA','汉萨商会'),
('icon','ICON_District_HARBOR','ICON_District_HARBOR','港口'),
('icon','ICON_District_HOLY_SITE','ICON_District_HOLY_SITE','圣地'),
('icon','ICON_District_INDUSTRIAL_ZONE','ICON_District_INDUSTRIAL_ZONE','工业区'),
('icon','ICON_District_LAVRA','ICON_District_LAVRA','修道院'),
('icon','ICON_District_MBANZA','ICON_District_MBANZA','姆班扎'),
('icon','ICON_District_NEIGHBORHOOD','ICON_District_NEIGHBORHOOD','社区'),
('icon','ICON_District_ROYAL_NAVY_DOCKYARD','ICON_District_ROYAL_NAVY_DOCKYARD','皇家船坞'),
('icon','ICON_District_SPACEPORT','ICON_District_SPACEPORT','航天港'),
('icon','ICON_District_THEATER','ICON_District_THEATER','剧院广场'),
('icon','ICON_GreatAdmiral','ICON_GreatAdmiral','大海军统帅'),
('icon','ICON_GreatArtist','ICON_GreatArtist','大艺术家'),
('icon','ICON_GreatEngineer','ICON_GreatEngineer','大工程师'),
('icon','ICON_GreatMerchant','ICON_GreatMerchant','大商人'),
('icon','ICON_GreatGeneral','ICON_GreatGeneral','大军事家'),
('icon','ICON_GreatMusician','ICON_GreatMusician','大音乐家'),
('icon','ICON_GreatProphet','ICON_GreatProphet','大预言家'),
('icon','ICON_GreatScientist','ICON_GreatScientist','大科学家'),
('icon','ICON_GreatWriter','ICON_GreatWriter','大作家'),
('icon','ICON_GreatWork_Artifact_Ancient','ICON_GreatWork_Artifact_Ancient','古文物巨作'),
('icon','ICON_GreatWork_Artifact_Classical','ICON_GreatWork_Artifact_Classical','古典文物巨作'),
('icon','ICON_GreatWork_Artifact_Industrial','ICON_GreatWork_Artifact_Industrial','工业文物巨作'),
('icon','ICON_GreatWork_Artifact_Medieval','ICON_GreatWork_Artifact_Medieval','中世纪文物巨作'),
('icon','ICON_GreatWork_Artifact_Renaissance','ICON_GreatWork_Artifact_Renaissance','文艺复兴文物巨作'),
('icon','ICON_GreatWork_Landscape','ICON_GreatWork_Landscape','风景画巨作'),
('icon','ICON_GreatWork_Portrait','ICON_GreatWork_Portrait','肖像画巨作'),
('icon','ICON_GreatWork_Relic','ICON_GreatWork_Relic','圣物'),
('icon','ICON_GreatWork_Religious','ICON_GreatWork_Religious','宗教题材巨作'),
('icon','ICON_GreatWork_Sculpture','ICON_GreatWork_Sculpture','雕塑巨作'),
('icon','ICON_GreatWork_Writing','ICON_GreatWork_Writing','著作巨作'),
('icon','ICON_VisLimited','ICON_VisLimited','有限可见'),
('icon','ICON_VisOpen','ICON_VisOpen','公开可见'),
('icon','ICON_VisSecret','ICON_VisSecret','私密可见'),
('icon','ICON_RESOURCE_ANTIQUITY_SITE','ICON_RESOURCE_ANTIQUITY_SITE','古物遗迹资源'),
('icon','ICON_RESOURCE_ALUMINUM','ICON_RESOURCE_ALUMINUM','铝'),
('icon','ICON_RESOURCE_SHIPWRECK','ICON_RESOURCE_SHIPWRECK','沉船遗迹'),
('icon','ICON_RESOURCE_BANANAS','ICON_RESOURCE_BANANAS','香蕉'),
('icon','ICON_RESOURCE_CATTLE','ICON_RESOURCE_CATTLE','牛'),
('icon','ICON_RESOURCE_CINNAMON','ICON_RESOURCE_CINNAMON','肉桂'),
('icon','ICON_RESOURCE_CITRUS','ICON_RESOURCE_CITRUS','柑橘'),
('icon','ICON_RESOURCE_CLOVES','ICON_RESOURCE_CLOVES','丁香'),
('icon','ICON_RESOURCE_COAL','ICON_RESOURCE_COAL','煤炭'),
('icon','ICON_RESOURCE_COCOA','ICON_RESOURCE_COCOA','可可'),
('icon','ICON_RESOURCE_COFFEE','ICON_RESOURCE_COFFEE','咖啡'),
('icon','ICON_RESOURCE_COPPER','ICON_RESOURCE_COPPER','铜'),
('icon','ICON_RESOURCE_COSMETICS','ICON_RESOURCE_COSMETICS','奢侈品化妆品'),
('icon','ICON_RESOURCE_COTTON','ICON_RESOURCE_COTTON','棉花'),
('icon','ICON_RESOURCE_CRABS','ICON_RESOURCE_CRABS','螃蟹'),
('icon','ICON_RESOURCE_DEER','ICON_RESOURCE_DEER','鹿'),
('icon','ICON_RESOURCE_DIAMONDS','ICON_RESOURCE_DIAMONDS','钻石'),
('icon','ICON_RESOURCE_DYES','ICON_RESOURCE_DYES','染料'),
('icon','ICON_RESOURCE_FURS','ICON_RESOURCE_FURS','毛皮'),
('icon','ICON_RESOURCE_GYPSUM','ICON_RESOURCE_GYPSUM','石膏'),
('icon','ICON_RESOURCE_GOLD','ICON_RESOURCE_GOLD','黄金'),
('icon','ICON_RESOURCE_HORSE','ICON_RESOURCE_HORSE','马匹'),
('icon','ICON_RESOURCE_INCENSE','ICON_RESOURCE_INCENSE','熏香'),
('icon','ICON_RESOURCE_IRON','ICON_RESOURCE_IRON','铁'),
('icon','ICON_RESOURCE_IVORY','ICON_RESOURCE_IVORY','象牙'),
('icon','ICON_RESOURCE_JADE','ICON_RESOURCE_JADE','玉石'),
('icon','ICON_RESOURCE_MARBLE','ICON_RESOURCE_MARBLE','大理石'),
('icon','ICON_RESOURCE_MERCURY','ICON_RESOURCE_MERCURY','水银'),
('icon','ICON_RESOURCE_NITER','ICON_RESOURCE_NITER','硝石'),
('icon','ICON_RESOURCE_OIL','ICON_RESOURCE_OIL','石油'),
('icon','ICON_RESOURCE_PEARLS','ICON_RESOURCE_PEARLS','珍珠'),
('icon','ICON_RESOURCE_PERFUME','ICON_RESOURCE_PERFUME','香水'),
('icon','ICON_RESOURCE_RICE','ICON_RESOURCE_RICE','稻米'),
('icon','ICON_RESOURCE_SALT','ICON_RESOURCE_SALT','盐'),
('icon','ICON_RESOURCE_SHEEP','ICON_RESOURCE_SHEEP','绵羊'),
('icon','ICON_RESOURCE_SILK','ICON_RESOURCE_SILK','丝绸'),
('icon','ICON_RESOURCE_SILVER','ICON_RESOURCE_SILVER','白银'),
('icon','ICON_RESOURCE_SPICES','ICON_RESOURCE_SPICES','香料'),
('icon','ICON_RESOURCE_STONE','ICON_RESOURCE_STONE','石材'),
('icon','ICON_RESOURCE_SUGAR','ICON_RESOURCE_SUGAR','蔗糖'),
('icon','ICON_RESOURCE_TEA','ICON_RESOURCE_TEA','茶叶'),
('icon','ICON_RESOURCE_TOBACCO','ICON_RESOURCE_TOBACCO','烟草'),
('icon','ICON_RESOURCE_TOYS','ICON_RESOURCE_TOYS','玩具'),
('icon','ICON_RESOURCE_TRUFFLES','ICON_RESOURCE_TRUFFLES','松露'),
('icon','ICON_RESOURCE_URANIUM','ICON_RESOURCE_URANIUM','铀'),
('icon','ICON_RESOURCE_WHALES','ICON_RESOURCE_WHALES','鲸鱼'),
('icon','ICON_RESOURCE_WHEAT','ICON_RESOURCE_WHEAT','小麦'),
('icon','ICON_CapitalLarge','ICON_CapitalLarge','大号首都图标'),
('icon','ICON_CultureLarge','ICON_CultureLarge','大号文化图标'),
('icon','ICON_FaithLarge','ICON_FaithLarge','大号信仰图标'),
('icon','ICON_FoodLarge','ICON_FoodLarge','大号食物图标'),
('icon','ICON_GoldLarge','ICON_GoldLarge','大号金币图标'),
('icon','ICON_ProductionLarge','ICON_ProductionLarge','大号产能图标'),
('icon','ICON_ScienceLarge','ICON_ScienceLarge','大号科技图标'),
('icon','ICON_TourismLarge','ICON_TourismLarge','大号旅游图标'),
('icon','ICON_VisLimitedLarge','ICON_VisLimitedLarge','大号有限可见'),
('icon','ICON_VisOpenLarge','ICON_VisOpenLarge','大号公开可见'),
('icon','ICON_VisSecretLarge','ICON_VisSecretLarge','大号私密可见'),
('icon','ICON_Bombard_Large','ICON_Bombard_Large','大号轰击图标'),
('icon','ICON_Charges_Large','ICON_Charges_Large','大号充能图标'),
('icon','ICON_Movement_Large','ICON_Movement_Large','大号移动力图标'),
('icon','ICON_Range_Large','ICON_Range_Large','大号射程图标'),
('icon','ICON_RangedStrength_Large','ICON_RangedStrength_Large','大号远程战力'),
('icon','ICON_ReligionStat_Large','ICON_ReligionStat_Large','大号宗教统计'),
('icon','ICON_TradingPostLarge','ICON_TradingPostLarge','大号贸易站'),
('icon','ICON_TradeRouteLarge','ICON_TradeRouteLarge','大号贸易路线'),
('icon','ICON_ALLIANCE','ICON_ALLIANCE','同盟'),
('icon','ICON_DECLARE_COLONIAL_WAR','ICON_DECLARE_COLONIAL_WAR','殖民战争宣战'),
('icon','ICON_DECLARE_FORMAL_WAR','ICON_DECLARE_FORMAL_WAR','正式战争宣战'),
('icon','ICON_DECLARE_FRIENDSHIP','ICON_DECLARE_FRIENDSHIP','宣告友好'),
('icon','ICON_DECLARE_HOLY_WAR','ICON_DECLARE_HOLY_WAR','圣战宣战'),
('icon','ICON_DECLARE_LIBERATION_WAR','ICON_DECLARE_LIBERATION_WAR','解放战争宣战'),
('icon','ICON_DECLARE_PROTECTORATE_WAR','ICON_DECLARE_PROTECTORATE_WAR','保护国战争宣战'),
('icon','ICON_DECLARE_RECONQUEST_WAR','ICON_DECLARE_RECONQUEST_WAR','收复战争宣战'),
('icon','ICON_DECLARE_TERRITORIAL_WAR','ICON_DECLARE_TERRITORIAL_WAR','领土战争宣战'),
('icon','ICON_DECLARE_SURPRISE_WAR','ICON_DECLARE_SURPRISE_WAR','突袭战争宣战'),
('icon','ICON_DECLARE_WAR_MINOR_CIV','ICON_DECLARE_WAR_MINOR_CIV','对城邦宣战'),
('icon','ICON_DEFENSIVE_PACT','ICON_DEFENSIVE_PACT','防御协定'),
('icon','ICON_DEMAND_TRIBUTE','ICON_DEMAND_TRIBUTE','索要贡金'),
('icon','ICON_DIPLOMATIC_DELEGATION','ICON_DIPLOMATIC_DELEGATION','外交代表团'),
('icon','ICON_GIFT_UNIT','ICON_GIFT_UNIT','赠送单位'),
('icon','ICON_GRANT_INFLUENCE_TOKEN','ICON_GRANT_INFLUENCE_TOKEN','授予影响力代币'),
('icon','ICON_MILITARY_ACCESS','ICON_MILITARY_ACCESS','军事通行权'),
('icon','ICON_OPEN_BORDERS','ICON_OPEN_BORDERS','开放边境'),
('icon','ICON_RECALL_AMBASSADOR','ICON_RECALL_AMBASSADOR','召回大使'),
('icon','ICON_REQUEST_ASSISTANCE','ICON_REQUEST_ASSISTANCE','请求援助'),
('icon','ICON_RESCHEDULE_TRADE','ICON_RESCHEDULE_TRADE','调整贸易'),
('icon','ICON_RESIDENT_EMBASSY','ICON_RESIDENT_EMBASSY','常驻大使馆'),
('icon','ICON_USE_NUCLEAR_WEAPON','ICON_USE_NUCLEAR_WEAPON','使用核武器'),
('icon','ICON_VIEW_DEMAND_TRIBUTE','ICON_VIEW_DEMAND_TRIBUTE','查看贡金要求'),
('icon','ICON_VIEW_MESSAGES','ICON_VIEW_MESSAGES','查看消息'),
('icon','ICON_PROMISES_ESPIONAGE','ICON_PROMISES_ESPIONAGE','间谍相关承诺'),
('icon','ICON_PROMISES_CITYSTATE','ICON_PROMISES_CITYSTATE','城邦相关承诺'),
('icon','ICON_PROMISES_RELIGION','ICON_PROMISES_RELIGION','宗教相关承诺'),
('icon','ICON_GreatWork_Artifact_Anc_Themed','ICON_GreatWork_Artifact_Anc_Themed','主题化古文物'),
('icon','ICON_GreatWork_Artifact_Class_Themed','ICON_GreatWork_Artifact_Class_Themed','主题化古典文物'),
('icon','ICON_GreatWork_Artifact_Industrial_Themed','ICON_GreatWork_Artifact_Industrial_Themed','主题化工业文物'),
('icon','ICON_GreatWork_Artifact_Medieval_Themed','ICON_GreatWork_Artifact_Medieval_Themed','主题化中世纪文物'),
('icon','ICON_GreatWork_Artifact_Renaissance_Themed','ICON_GreatWork_Artifact_Renaissance_Themed','主题化文艺复兴文物'),
('icon','ICON_GreatWork_Landscape_Themed','ICON_GreatWork_Landscape_Themed','主题化风景画'),
('icon','ICON_GreatWork_Music_Themed','ICON_GreatWork_Music_Themed','主题化音乐'),
('icon','ICON_GreatWork_Portrait_Themed','ICON_GreatWork_Portrait_Themed','主题化肖像画'),
('icon','ICON_GreatWork_Relic_Themed','ICON_GreatWork_Relic_Themed','主题化圣物'),
('icon','ICON_GreatWork_Religious_Themed','ICON_GreatWork_Religious_Themed','主题化宗教作品'),
('icon','ICON_GreatWork_Sculpture_Themed','ICON_GreatWork_Sculpture_Themed','主题化雕塑'),
('icon','ICON_GreatWork_Writing_Themed','ICON_GreatWork_Writing_Themed','主题化著作');